sudo: required
dist: trusty

language: cpp

branches:
  only:
    - master
    - travis

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_VERSION="3.8"
    - CMAKE_VERSION_FULL="3.8.2"

cache:
  ccache: true
  directories:
    - ${DEPS_DIR}/cmake-${CMAKE_VERSION_FULL}-Linux-x86_64/bin
    - ${DEPS_DIR}/cmake-${CMAKE_VERSION_FULL}-Linux-x86_64/plugins
    - ${DEPS_DIR}/cmake-${CMAKE_VERSION_FULL}-Linux-x86_64/share

matrix:
  include:
    - os: osx
    - os: linux
      - compiler: gcc
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-4.9
        env: COMPILER=g++-4.9
      - compiler: gcc
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-5
        env: COMPILER=g++-5
      - compiler: clang
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-3.9
            packages:
              - clang-3.9
        env: COMPILER=clang++-3.9
      - compiler: clang
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-4.0
            packages:
              - clang-4.0
        env: COMPILER=clang++-4.0

install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" && ! -f "cmake-${CMAKE_VERSION_FULL}-Linux-x86_64/bin/cmake" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION_FULL}-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then sudo apt update ; fi
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then sudo apt install libc++-dev ; fi


script:
  - mkdir build
  - cd build
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make ; fi
  - if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then cmake .. && make ; fi
  - ./tests/psychic-color-tests
